[package]
name = "aoc-2022"
version = "0.0.0"
edition = "2021"
authors.workspace = true
description = "Advent of Code library for the 2022 puzzles"
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
