[workspace]
members = ["aoc", "aoc-2022", "common"]

[workspace.package]
authors = ["Creberus <creberus@tutanota.com>"]
readme = "README.md"
repository = "https://github.com/Creberus/advent-of-code"
license-file = "LICENSE"
keywords = ["adventofcode"]
publish = false

